const paypalSupportedCurrencies = [
    {
        "code": "AUD",
        "symbol": "$",
        "name": "Australian Dollar",
        "countryKeywords": ["AUD", "Australia", "AU"],
        "supportsDecimals": true
    },
    {
        "code": "BRL",
        "symbol": "R$",
        "name": "Brazilian Real",
        "countryKeywords": ["BRL", "Brazil", "BR"],
        "supportsDecimals": true
    },
    {
        "code": "CAD",
        "symbol": "$",
        "name": "Canadian Dollar",
        "countryKeywords": ["CAD", "Canada", "CA"],
        "supportsDecimals": true
    },
    {
        "code": "CNY",
        "symbol": "¥",
        "name": "Chinese Renminbi",
        "countryKeywords": ["CNY", "China", "CN", "Yuan"],
        "supportsDecimals": true
    },
    {
        "code": "CZK",
        "symbol": "Kč",
        "name": "Czech Koruna",
        "countryKeywords": ["CZK", "Czech Republic", "CZ"],
        "supportsDecimals": true
    },
    {
        "code": "DKK",
        "symbol": "kr",
        "name": "Danish Krone",
        "countryKeywords": ["DKK", "Denmark", "DK"],
        "supportsDecimals": true
    },
    {
        "code": "EUR",
        "symbol": "€",
        "name": "Euro",
        "countryKeywords": ["EUR", "Eurozone", "EU"],
        "supportsDecimals": true
    },
    {
        "code": "HKD",
        "symbol": "$",
        "name": "Hong Kong Dollar",
        "countryKeywords": ["HKD", "Hong Kong", "HK"],
        "supportsDecimals": true
    },
    {
        "code": "HUF",
        "symbol": "Ft",
        "name": "Hungarian Forint",
        "countryKeywords": ["HUF", "Hungary", "HU"],
        "supportsDecimals": false
    },
    {
        "code": "ILS",
        "symbol": "₪",
        "name": "Israeli New Shekel",
        "countryKeywords": ["ILS", "Israel", "IL"],
        "supportsDecimals": true
    },
    {
        "code": "JPY",
        "symbol": "¥",
        "name": "Japanese Yen",
        "countryKeywords": ["JPY", "Japan", "JP"],
        "supportsDecimals": false
    },
    {
        "code": "MYR",
        "symbol": "RM",
        "name": "Malaysian Ringgit",
        "countryKeywords": ["MYR", "Malaysia", "MY"],
        "supportsDecimals": true
    },
    {
        "code": "MXN",
        "symbol": "$",
        "name": "Mexican Peso",
        "countryKeywords": ["MXN", "Mexico", "MX"],
        "supportsDecimals": true
    },
    {
        "code": "TWD",
        "symbol": "NT$",
        "name": "New Taiwan Dollar",
        "countryKeywords": ["TWD", "Taiwan", "TW"],
        "supportsDecimals": false
    },
    {
        "code": "NZD",
        "symbol": "$",
        "name": "New Zealand Dollar",
        "countryKeywords": ["NZD", "New Zealand", "NZ"],
        "supportsDecimals": true
    },
    {
        "code": "NOK",
        "symbol": "kr",
        "name": "Norwegian Krone",
        "countryKeywords": ["NOK", "Norway", "NO"],
        "supportsDecimals": true
    },
    {
        "code": "PHP",
        "symbol": "₱",
        "name": "Philippine Peso",
        "countryKeywords": ["PHP", "Philippines", "PH"],
        "supportsDecimals": true
    },
    {
        "code": "PLN",
        "symbol": "zł",
        "name": "Polish Złoty",
        "countryKeywords": ["PLN", "Poland", "PL"],
        "supportsDecimals": true
    },
    {
        "code": "GBP",
        "symbol": "£",
        "name": "Pound Sterling",
        "countryKeywords": ["GBP", "United Kingdom", "UK", "Britain"],
        "supportsDecimals": true
    },
    {
        "code": "SGD",
        "symbol": "$",
        "name": "Singapore Dollar",
        "countryKeywords": ["SGD", "Singapore", "SG"],
        "supportsDecimals": true
    },
    {
        "code": "SEK",
        "symbol": "kr",
        "name": "Swedish Krona",
        "countryKeywords": ["SEK", "Sweden", "SE"],
        "supportsDecimals": true
    },
    {
        "code": "CHF",
        "symbol": "CHF",
        "name": "Swiss Franc",
        "countryKeywords": ["CHF", "Switzerland", "CH"],
        "supportsDecimals": true
    },
    {
        "code": "THB",
        "symbol": "฿",
        "name": "Thai Baht",
        "countryKeywords": ["THB", "Thailand", "TH"],
        "supportsDecimals": true
    },
    {
        "code": "USD",
        "symbol": "$",
        "name": "United States Dollar",
        "countryKeywords": ["USD", "United States", "US", "America"],
        "supportsDecimals": true
    }
]

const wiseSupportedCurrencies = [
    {
        "code": "AED",
        "symbol": "د.إ",
        "name": "United Arab Emirates dirham",
        "countryKeywords": [
            "AED",
            "AE",
            "are",
            "United Arab Emirates",
            "Dubai"
        ],
        "supportsDecimals": true
    },
    {
        "code": "AFN",
        "symbol": "؋",
        "name": "Afghanistan afghani",
        "countryKeywords": [
            "Afghanistan",
            "afg",
            "AF",
            "AFN"
        ],
        "supportsDecimals": true
    },
    {
        "code": "ALL",
        "symbol": "Lek",
        "name": "Albanian lek",
        "countryKeywords": [
            "ALL",
            "alb",
            "AL",
            "Albania"
        ],
        "supportsDecimals": true
    },
    {
        "code": "AMD",
        "symbol": "֏",
        "name": "Armenian dram",
        "countryKeywords": [
            "Armenia",
            "AMD",
            "AM",
            "arm"
        ],
        "supportsDecimals": true
    },
    {
        "code": "ANG",
        "symbol": "ƒ",
        "name": "Netherlands Antillean guilder",
        "countryKeywords": [
            "CW",
            "cuw",
            "Sint Maarten (Dutch part)",
            "SX",
            "ant",
            "Netherlands Antilles",
            "sxm",
            "ANG",
            "Curaçao",
            "AN"
        ],
        "supportsDecimals": true
    },
    {
        "code": "AOA",
        "symbol": "Kz",
        "name": "Angolan kwanza",
        "countryKeywords": [
            "AOA",
            "Angola",
            "ago",
            "AO"
        ],
        "supportsDecimals": true
    },
    {
        "code": "ARS",
        "symbol": "$",
        "name": "Argentine peso",
        "countryKeywords": [
            "AR",
            "ARS",
            "Argentina",
            "arg"
        ],
        "supportsDecimals": true
    },
    {
        "code": "AUD",
        "symbol": "A$",
        "name": "Australian dollar",
        "countryKeywords": [
            "TV",
            "NR",
            "HM",
            "Christmas Island",
            "cck",
            "Kiribati",
            "AUD",
            "tuv",
            "kir",
            "Cocos (Keeling) Islands",
            "cxr",
            "KI",
            "CC",
            "Heard Island and McDonald Islands",
            "Tuvalu",
            "Norfolk Island",
            "nru",
            "nfk",
            "AU",
            "CX",
            "NF",
            "Nauru",
            "Australia",
            "hmd",
            "aus"
        ],
        "supportsDecimals": true
    },
    {
        "code": "AWG",
        "symbol": "AWG",
        "name": "Aruban florin",
        "countryKeywords": [
            "AWG",
            "AW",
            "abw",
            "Aruba"
        ],
        "supportsDecimals": true
    },
    {
        "code": "AZN",
        "symbol": "man.",
        "name": "Azerbaijani manat",
        "countryKeywords": [
            "Azerbaijan",
            "AZN",
            "AZ",
            "aze"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BAM",
        "symbol": "KM",
        "name": "Bosnia and Herzegovina convertible mark",
        "countryKeywords": [
            "bih",
            "Bosnia and Herzegovina",
            "BAM",
            "BA"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BBD",
        "symbol": "BBD",
        "name": "Barbadian dollar",
        "countryKeywords": [
            "BB",
            "brb",
            "Barbados",
            "BBD"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BDT",
        "symbol": "Tk",
        "name": "Bangladeshi taka",
        "countryKeywords": [
            "BD",
            "Bangladesh",
            "BDT",
            "bgd"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BGN",
        "symbol": "лв",
        "name": "Bulgarian lev",
        "countryKeywords": [
            "BG",
            "BGN",
            "bgr",
            "Bulgaria"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BHD",
        "symbol": "BHD",
        "name": "Bahraini dinar",
        "countryKeywords": [
            "BH",
            "bhr",
            "Bahrain",
            "BHD"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BIF",
        "symbol": "BIF",
        "name": "Burundian franc",
        "countryKeywords": [
            "Burundi",
            "bdi",
            "BI",
            "BIF"
        ],
        "supportsDecimals": false
    },
    {
        "code": "BMD",
        "symbol": "BMD",
        "name": "Bermudian dollar",
        "countryKeywords": [
            "BMD",
            "Bermuda",
            "BM",
            "bmu"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BND",
        "symbol": "BND",
        "name": "Brunei dollar",
        "countryKeywords": [
            "BND",
            "BN",
            "Brunei Darussalam",
            "brn"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BOB",
        "symbol": "BOB",
        "name": "Bolivian boliviano",
        "countryKeywords": [
            "BOB",
            "Bolivia",
            "BO",
            "bol"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BRL",
        "symbol": "R$",
        "name": "Brazilian real",
        "countryKeywords": [
            "BR",
            "bra",
            "Brazil",
            "BRL"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BSD",
        "symbol": "BSD",
        "name": "Bahamian dollar",
        "countryKeywords": [
            "BS",
            "BSD",
            "bhs",
            "Bahamas"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BTN",
        "symbol": "BTN",
        "name": "Bhutanese ngultrum",
        "countryKeywords": [
            "BT",
            "Bhutan",
            "BTN",
            "btn"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BWP",
        "symbol": "BWP",
        "name": "Botswana pula",
        "countryKeywords": [
            "BW",
            "Botswana",
            "BWP",
            "bwa"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BYN",
        "symbol": "BYN",
        "name": "Belarusian ruble",
        "countryKeywords": [
            "BYN",
            "BY",
            "blr",
            "Belarus"
        ],
        "supportsDecimals": true
    },
    {
        "code": "BZD",
        "symbol": "BZ$",
        "name": "Belizean dollar",
        "countryKeywords": [
            "blz",
            "BZ",
            "Belize",
            "BZD"
        ],
        "supportsDecimals": true
    },
    {
        "code": "CAD",
        "symbol": "C$",
        "name": "Canadian dollar",
        "countryKeywords": [
            "can",
            "Canada",
            "CAD",
            "CA"
        ],
        "supportsDecimals": true
    },
    {
        "code": "CDF",
        "symbol": "CDF",
        "name": "Congolese franc",
        "countryKeywords": [
            "CD",
            "CDF",
            "cod",
            "Congo, the Democratic Republic of the"
        ],
        "supportsDecimals": true
    },
    {
        "code": "CHF",
        "symbol": "SFr.",
        "name": "Swiss franc",
        "countryKeywords": [
            "CHF",
            "che",
            "CH",
            "Liechtenstein",
            "lie",
            "LI",
            "Switzerland"
        ],
        "supportsDecimals": true
    },
    {
        "code": "CLP",
        "symbol": "$",
        "name": "Chilean peso",
        "countryKeywords": [
            "CLP",
            "chl",
            "CL",
            "Chile"
        ],
        "supportsDecimals": false
    },
    {
        "code": "CNH",
        "symbol": "¥",
        "name": "Chinese yuan",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "CNY",
        "symbol": "¥",
        "name": "Chinese yuan",
        "countryKeywords": [
            "China",
            "chn",
            "CN",
            "CNY"
        ],
        "supportsDecimals": true
    },
    {
        "code": "COP",
        "symbol": "$",
        "name": "Colombian peso",
        "countryKeywords": [
            "col",
            "Colombia",
            "COP",
            "CO"
        ],
        "supportsDecimals": true
    },
    {
        "code": "CRC",
        "symbol": "₡",
        "name": "Costa Rican colón",
        "countryKeywords": [
            "CRC",
            "cri",
            "CR",
            "Costa Rica"
        ],
        "supportsDecimals": true
    },
    {
        "code": "CUC",
        "symbol": "CUC$",
        "name": "Cuban Convertible peso",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "CUP",
        "symbol": "CUP",
        "name": "Cuban peso",
        "countryKeywords": [
            "cub",
            "Cuba",
            "CU",
            "CUP"
        ],
        "supportsDecimals": true
    },
    {
        "code": "CVE",
        "symbol": "CVE",
        "name": "Cape Verdean escudo",
        "countryKeywords": [
            "Cape Verde",
            "CVE",
            "CV",
            "cpv"
        ],
        "supportsDecimals": true
    },
    {
        "code": "CZK",
        "symbol": "Kč",
        "name": "Czech koruna",
        "countryKeywords": [
            "Czech Republic",
            "CZK",
            "CZ",
            "cze"
        ],
        "supportsDecimals": true
    },
    {
        "code": "DJF",
        "symbol": "DJF",
        "name": "Djiboutian franc",
        "countryKeywords": [
            "Djibouti",
            "DJF",
            "dji",
            "DJ"
        ],
        "supportsDecimals": false
    },
    {
        "code": "DKK",
        "symbol": "kr",
        "name": "Danish krone",
        "countryKeywords": [
            "dnk",
            "grl",
            "fro",
            "DKK",
            "GL",
            "DK",
            "Faroe Islands",
            "Denmark",
            "FO",
            "Greenland"
        ],
        "supportsDecimals": true
    },
    {
        "code": "DOP",
        "symbol": "$",
        "name": "Dominican peso",
        "countryKeywords": [
            "dom",
            "DOP",
            "Dominican Republic",
            "DO"
        ],
        "supportsDecimals": true
    },
    {
        "code": "DZD",
        "symbol": "DZD",
        "name": "Algerian dinar",
        "countryKeywords": [
            "DZ",
            "dza",
            "Algeria",
            "DZD"
        ],
        "supportsDecimals": true
    },
    {
        "code": "EGP",
        "symbol": "E£",
        "name": "Egyptian pound",
        "countryKeywords": [
            "EG",
            "egy",
            "Egypt",
            "EGP"
        ],
        "supportsDecimals": true
    },
    {
        "code": "ERN",
        "symbol": "ERN",
        "name": "Eritrean nakfa",
        "countryKeywords": [
            "ERN",
            "Eritrea",
            "ER",
            "eri"
        ],
        "supportsDecimals": true
    },
    {
        "code": "ETB",
        "symbol": "Br",
        "name": "Ethiopian birr",
        "countryKeywords": [
            "ETB",
            "eth",
            "Ethiopia",
            "ET"
        ],
        "supportsDecimals": true
    },
    {
        "code": "EUR",
        "symbol": "€",
        "name": "Euro",
        "countryKeywords": [
            "Cambodia",
            "fin",
            "cck",
            "Paraguay",
            "lux",
            "uga",
            "Solomon Islands",
            "iot",
            "Montserrat",
            "deu",
            "egy",
            "Guadeloupe",
            "lva",
            "hnd",
            "nzl",
            "AD",
            "fji",
            "AE",
            "Falkland Islands",
            "AG",
            "Seychelles",
            "AI",
            "glp",
            "AL",
            "AM",
            "Bahrain",
            "AO",
            "wlf",
            "AR",
            "AS",
            "AT",
            "AU",
            "AW",
            "Finland",
            "AX",
            "Faroe Islands",
            "AZ",
            "gmb",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "mys",
            "BH",
            "BJ",
            "myt",
            "BL",
            "BM",
            "BN",
            "BO",
            "BS",
            "BT",
            "BW",
            "Cocos (Keeling) Islands",
            "Liechtenstein",
            "gnb",
            "Bulgaria",
            "sen",
            "CA",
            "CC",
            "irl",
            "flk",
            "CH",
            "qat",
            "CI",
            "CK",
            "CL",
            "Côte d'Ivoire",
            "CN",
            "United Arab Emirates",
            "Kenya",
            "tha",
            "French Polynesia",
            "CR",
            "CV",
            "Saint Lucia",
            "CX",
            "CY",
            "abw",
            "CZ",
            "Mayotte",
            "Israel",
            "San Marino",
            "Tajikistan",
            "DE",
            "isl",
            "Gibraltar",
            "Cyprus",
            "DK",
            "bel",
            "kwt",
            "isr",
            "DM",
            "Malaysia",
            "ben",
            "DO",
            "Armenia",
            "DZ",
            "ita",
            "Turks and Caicos Islands",
            "bfa",
            "pan",
            "sgp",
            "ukr",
            "EC",
            "EE",
            "che",
            "Ecuador",
            "EG",
            "reu",
            "chl",
            "chn",
            "hrv",
            "ES",
            "ET",
            "tjk",
            "vnm",
            "shn",
            "Italy",
            "bgd",
            "Haiti",
            "FI",
            "FJ",
            "FK",
            "FM",
            "American Samoa",
            "FO",
            "bgr",
            "FR",
            "Vatican City",
            "civ",
            "grd",
            "grc",
            "GA",
            "GB",
            "hti",
            "GD",
            "Kyrgyzstan",
            "GE",
            "GF",
            "grl",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "Uzbekistan",
            "GP",
            "GR",
            "bhs",
            "GT",
            "bhr",
            "GW",
            "GY",
            "dma",
            "tls",
            "Dominica",
            "hun",
            "bih",
            "Benin",
            "HK",
            "HN",
            "ago",
            "HR",
            "HT",
            "Portugal",
            "HU",
            "Grenada",
            "wsm",
            "Mongolia",
            "Latvia",
            "Morocco",
            "fra",
            "Guatemala",
            "ID",
            "nam",
            "per",
            "IE",
            "dnk",
            "gtm",
            "fro",
            "IL",
            "IM",
            "IN",
            "IO",
            "Tanzania",
            "slb",
            "IS",
            "Ghana",
            "IT",
            "sle",
            "India",
            "Canada",
            "Maldives",
            "Kosovo, Republic of",
            "Taiwan",
            "aia",
            "guf",
            "JE",
            "slv",
            "Germany",
            "fsm",
            "dom",
            "Fiji",
            "JM",
            "United States",
            "Guinea",
            "JP",
            "Micronesia, Federated States of",
            "Sao Tome and Principe",
            "guy",
            "mac",
            "Costa Rica",
            "Vietnam",
            "ton",
            "maf",
            "ncl",
            "smr",
            "KE",
            "KG",
            "KH",
            "mar",
            "blm",
            "KN",
            "Timor-Leste",
            "KR",
            "KW",
            "Switzerland",
            "KY",
            "Samoa",
            "Spain",
            "KZ",
            "phl",
            "LA",
            "LB",
            "LC",
            "Palau",
            "LI",
            "ury",
            "cok",
            "LK",
            "Estonia",
            "usa",
            "esp",
            "LR",
            "LS",
            "est",
            "LT",
            "LU",
            "LV",
            "bmu",
            "Niue",
            "Mozambique",
            "vut",
            "El Salvador",
            "MA",
            "alb",
            "MC",
            "MD",
            "ala",
            "eth",
            "mco",
            "ME",
            "MF",
            "ner",
            "lao",
            "MH",
            "Lesotho",
            "MK",
            "Tonga",
            "ML",
            "MN",
            "MO",
            "EUR",
            "MQ",
            "MR",
            "MS",
            "MT",
            "cpv",
            "MU",
            "MV",
            "MW",
            "mda",
            "MX",
            "MY",
            "MZ",
            "Mauritius",
            "Norfolk Island",
            "spm",
            "nfk",
            "NA",
            "NC",
            "NE",
            "NF",
            "lbn",
            "NI",
            "lbr",
            "mdv",
            "NL",
            "bol",
            "NO",
            "NP",
            "NR",
            "NU",
            "lca",
            "NZ",
            "Malta",
            "Cape Verde",
            "Ireland",
            "and",
            "rou",
            "cri",
            "Lithuania",
            "France",
            "OM",
            "mex",
            "srb",
            "kaz",
            "tto",
            "PA",
            "Nicaragua",
            "Norway",
            "PE",
            "PF",
            "Macao",
            "PG",
            "PH",
            "Uganda",
            "Mexico",
            "Suriname",
            "plw",
            "PL",
            "PM",
            "Greenland",
            "Saint Helena",
            "Papua New Guinea",
            "PT",
            "PW",
            "nic",
            "PY",
            "tun",
            "Kazakhstan",
            "Åland Islands",
            "Bahamas",
            "QA",
            "tur",
            "brb",
            "tuv",
            "Marshall Islands",
            "Mali",
            "Panama",
            "jam",
            "niu",
            "Laos",
            "zaf",
            "brn",
            "Argentina",
            "png",
            "Zambia",
            "stp",
            "mhl",
            "Guinea-Bissau",
            "RE",
            "Macedonia, Former Yugoslav Republic of",
            "Namibia",
            "Georgia",
            "Saint Kitts and Nevis",
            "RO",
            "RS",
            "RW",
            "twn",
            "Aruba",
            "pol",
            "Dubai",
            "SA",
            "SB",
            "SC",
            "sur",
            "omn",
            "SE",
            "Sweden",
            "SG",
            "ken",
            "are",
            "Malawi",
            "SH",
            "Andorra",
            "SI",
            "arg",
            "SK",
            "Poland",
            "SL",
            "SM",
            "SN",
            "uzb",
            "Tunisia",
            "btn",
            "arm",
            "SR",
            "ST",
            "SV",
            "nld",
            "svk",
            "svn",
            "Tuvalu",
            "TC",
            "Lebanon",
            "Azerbaijan",
            "TF",
            "Czech Republic",
            "Mauritania",
            "TH",
            "Guernsey",
            "TJ",
            "TL",
            "TN",
            "asm",
            "TO",
            "Australia",
            "TR",
            "swe",
            "TT",
            "TV",
            "TW",
            "TZ",
            "mkd",
            "lie",
            "dza",
            "UA",
            "Iceland",
            "Oman",
            "Gabon",
            "atf",
            "UG",
            "atg",
            "Luxembourg",
            "tza",
            "Algeria",
            "Jersey",
            "Slovenia",
            "cxr",
            "US",
            "jey",
            "kgz",
            "Antigua and Barbuda",
            "UY",
            "UZ",
            "Moldova",
            "VA",
            "mli",
            "VC",
            "bwa",
            "VG",
            "khm",
            "Vanuatu",
            "idn",
            "prt",
            "mlt",
            "cym",
            "pry",
            "VN",
            "Honduras",
            "cyp",
            "syc",
            "Nauru",
            "rwa",
            "aus",
            "VU",
            "aut",
            "Singapore",
            "lka",
            "French Guiana",
            "Christmas Island",
            "gab",
            "WF",
            "cze",
            "nor",
            "Netherlands",
            "China",
            "Martinique",
            "Saint Pierre and Miquelon",
            "WS",
            "Bhutan",
            "Romania",
            "mne",
            "Philippines",
            "mng",
            "npl",
            "XK",
            "gbr",
            "British Virgin Islands",
            "British Indian Ocean Territory",
            "Montenegro",
            "Indonesia",
            "Angola",
            "Brunei Darussalam",
            "New Caledonia",
            "Greece",
            "Cayman Islands",
            "Guyana",
            "moz",
            "YT",
            "Chile",
            "Nepal",
            "Isle of Man",
            "ZA",
            "Ukraine",
            "vat",
            "Anguilla",
            "nru",
            "Turkey",
            "ZM",
            "Belgium",
            "South Africa",
            "Trinidad and Tobago",
            "Bermuda",
            "Jamaica",
            "Peru",
            "Hong Kong",
            "Thailand",
            "aze",
            "geo",
            "Saint Martin (French part)",
            "Kuwait",
            "kna",
            "Croatia",
            "Sri Lanka",
            "Cook Islands",
            "Uruguay",
            "vct",
            "United Kingdom",
            "mrt",
            "Liberia",
            "Burkina Faso",
            "Saint Barthélemy",
            "pyf",
            "msr",
            "Wallis and Futuna",
            "zmb",
            "kor",
            "Austria",
            "South Korea",
            "Monaco",
            "ecu",
            "ggy",
            "gha",
            "Réunion",
            "Hungary",
            "Japan",
            "mtq",
            "Albania",
            "New Zealand",
            "Senegal",
            "Ethiopia",
            "gib",
            "hkg",
            "Egypt",
            "lso",
            "mus",
            "Sierra Leone",
            "imn",
            "Bolivia",
            "gin",
            "vgb",
            "Saudi Arabia",
            "can",
            "tca",
            "Gambia",
            "Qatar",
            "Slovakia",
            "Serbia",
            "Bosnia and Herzegovina",
            "ind",
            "xkx",
            "Niger",
            "sau",
            "Rwanda",
            "jpn",
            "French Southern Territories",
            "ltu",
            "Bangladesh",
            "Barbados",
            "Saint Vincent and the Grenadines",
            "Botswana",
            "Denmark",
            "Dominican Republic",
            "mwi"
        ],
        "supportsDecimals": true
    },
    {
        "code": "FJD",
        "symbol": "FJD",
        "name": "Fijian dollar",
        "countryKeywords": [
            "FJD",
            "Fiji",
            "FJ",
            "fji"
        ],
        "supportsDecimals": true
    },
    {
        "code": "FKP",
        "symbol": "£",
        "name": "Falkland Islands pound",
        "countryKeywords": [
            "South Georgia and the South Sandwich Islands",
            "flk",
            "Falkland Islands",
            "FK",
            "FKP",
            "GS",
            "sgs"
        ],
        "supportsDecimals": true
    },
    {
        "code": "GBP",
        "symbol": "£",
        "name": "British pound",
        "countryKeywords": [
            "PT",
            "fin",
            "tun",
            "Kazakhstan",
            "lux",
            "tur",
            "QA",
            "deu",
            "lva",
            "AD",
            "AE",
            "Seychelles",
            "AL",
            "Bahrain",
            "stp",
            "AT",
            "Macedonia, Former Yugoslav Republic of",
            "Finland",
            "Faroe Islands",
            "AZ",
            "Georgia",
            "RO",
            "BA",
            "RS",
            "BE",
            "BG",
            "BH",
            "pol",
            "Dubai",
            "SA",
            "SC",
            "SE",
            "Sweden",
            "are",
            "Andorra",
            "SI",
            "Liechtenstein",
            "SK",
            "Poland",
            "SM",
            "Bulgaria",
            "Tunisia",
            "ST",
            "irl",
            "CH",
            "qat",
            "nld",
            "svk",
            "svn",
            "United Arab Emirates",
            "CR",
            "Lebanon",
            "Azerbaijan",
            "Czech Republic",
            "Mauritania",
            "Saint Lucia",
            "Guernsey",
            "CY",
            "CZ",
            "TL",
            "TN",
            "Israel",
            "San Marino",
            "TR",
            "swe",
            "DE",
            "isl",
            "Gibraltar",
            "Cyprus",
            "DK",
            "mkd",
            "bel",
            "kwt",
            "isr",
            "lie",
            "DO",
            "UA",
            "Iceland",
            "Luxembourg",
            "ita",
            "Slovenia",
            "Jersey",
            "ukr",
            "jey",
            "EE",
            "che",
            "Moldova",
            "hrv",
            "ES",
            "VG",
            "prt",
            "mlt",
            "Italy",
            "cyp",
            "syc",
            "aut",
            "FI",
            "FO",
            "bgr",
            "FR",
            "cze",
            "nor",
            "Netherlands",
            "GBP",
            "grc",
            "GB",
            "GE",
            "GG",
            "grl",
            "GI",
            "Romania",
            "mne",
            "GL",
            "GR",
            "GT",
            "bhr",
            "gbr",
            "British Virgin Islands",
            "tls",
            "Montenegro",
            "hun",
            "bih",
            "HR",
            "HU",
            "Portugal",
            "Greece",
            "Latvia",
            "fra",
            "Guatemala",
            "IE",
            "dnk",
            "gtm",
            "fro",
            "IL",
            "IM",
            "Isle of Man",
            "Ukraine",
            "IS",
            "IT",
            "Turkey",
            "Belgium",
            "JE",
            "Germany",
            "dom",
            "Sao Tome and Principe",
            "aze",
            "Costa Rica",
            "geo",
            "smr",
            "Kuwait",
            "Croatia",
            "Timor-Leste",
            "United Kingdom",
            "KW",
            "Switzerland",
            "mrt",
            "Spain",
            "KZ",
            "LB",
            "LC",
            "LI",
            "Estonia",
            "esp",
            "est",
            "LT",
            "LU",
            "LV",
            "Austria",
            "Monaco",
            "alb",
            "MC",
            "MD",
            "mco",
            "ggy",
            "ME",
            "MK",
            "Hungary",
            "MR",
            "MT",
            "MU",
            "mda",
            "Mauritius",
            "Albania",
            "lbn",
            "NL",
            "NO",
            "gib",
            "mus",
            "lca",
            "imn",
            "Malta",
            "vgb",
            "Saudi Arabia",
            "Ireland",
            "and",
            "Qatar",
            "rou",
            "cri",
            "Slovakia",
            "Lithuania",
            "Serbia",
            "France",
            "Bosnia and Herzegovina",
            "srb",
            "kaz",
            "sau",
            "ltu",
            "Norway",
            "Denmark",
            "Dominican Republic",
            "PL",
            "Greenland"
        ],
        "supportsDecimals": true
    },
    {
        "code": "GEL",
        "symbol": "GEL",
        "name": "Georgian lari",
        "countryKeywords": [
            "geo",
            "Georgia",
            "GE",
            "GEL"
        ],
        "supportsDecimals": true
    },
    {
        "code": "GGP",
        "symbol": "£",
        "name": "Guernsey pound",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "GHS",
        "symbol": "GH¢",
        "name": "Ghanaian cedi",
        "countryKeywords": [
            "GH",
            "gha",
            "GHS",
            "Ghana"
        ],
        "supportsDecimals": true
    },
    {
        "code": "GIP",
        "symbol": "£",
        "name": "Gibraltar pound",
        "countryKeywords": [
            "gib",
            "GI",
            "Gibraltar",
            "GIP"
        ],
        "supportsDecimals": true
    },
    {
        "code": "GMD",
        "symbol": "GMD",
        "name": "Gambian dalasi",
        "countryKeywords": [
            "Gambia",
            "GM",
            "gmb",
            "GMD"
        ],
        "supportsDecimals": true
    },
    {
        "code": "GNF",
        "symbol": "GNF",
        "name": "Guinean franc",
        "countryKeywords": [
            "Guinea",
            "GN",
            "gin",
            "GNF"
        ],
        "supportsDecimals": false
    },
    {
        "code": "GTQ",
        "symbol": "Q",
        "name": "Guatemalan quetzal",
        "countryKeywords": [
            "gtm",
            "GTQ",
            "Guatemala",
            "GT"
        ],
        "supportsDecimals": true
    },
    {
        "code": "GYD",
        "symbol": "GYD",
        "name": "Guyanese dollar",
        "countryKeywords": [
            "GY",
            "GYD",
            "Guyana",
            "guy"
        ],
        "supportsDecimals": true
    },
    {
        "code": "HKD",
        "symbol": "$",
        "name": "Hong Kong dollar",
        "countryKeywords": [
            "HKD",
            "HK",
            "Hong Kong",
            "hkg"
        ],
        "supportsDecimals": true
    },
    {
        "code": "HNL",
        "symbol": "L",
        "name": "Honduran lempira",
        "countryKeywords": [
            "HN",
            "HNL",
            "Honduras",
            "hnd"
        ],
        "supportsDecimals": true
    },
    {
        "code": "HTG",
        "symbol": "HTG",
        "name": "Haitian gourde",
        "countryKeywords": [
            "Haiti",
            "HTG",
            "HT",
            "hti"
        ],
        "supportsDecimals": true
    },
    {
        "code": "HUF",
        "symbol": "Ft",
        "name": "Hungarian forint",
        "countryKeywords": [
            "hun",
            "Hungary",
            "HUF",
            "HU"
        ],
        "supportsDecimals": false
    },
    {
        "code": "IDR",
        "symbol": "Rp",
        "name": "Indonesian rupiah",
        "countryKeywords": [
            "idn",
            "IDR",
            "ID",
            "Indonesia"
        ],
        "supportsDecimals": false
    },
    {
        "code": "ILS",
        "symbol": "₪",
        "name": "Israeli shekel",
        "countryKeywords": [
            "ILS",
            "PS",
            "pse",
            "IL",
            "isr",
            "Israel",
            "Palestine"
        ],
        "supportsDecimals": true
    },
    {
        "code": "IMP",
        "symbol": "£",
        "name": "Isle of Man pound",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "INR",
        "symbol": "₹",
        "name": "Indian rupee",
        "countryKeywords": [
            "IN",
            "INR",
            "ind",
            "India"
        ],
        "supportsDecimals": true
    },
    {
        "code": "IQD",
        "symbol": "IQD",
        "name": "Iraqi dinar",
        "countryKeywords": [
            "IQ",
            "irq",
            "Iraq",
            "IQD"
        ],
        "supportsDecimals": true
    },
    {
        "code": "IRR",
        "symbol": "﷼",
        "name": "Iranian rial",
        "countryKeywords": [
            "irn",
            "Iran",
            "IRR",
            "IR"
        ],
        "supportsDecimals": true
    },
    {
        "code": "ISK",
        "symbol": "kr",
        "name": "Icelandic króna",
        "countryKeywords": [
            "ISK",
            "isl",
            "IS",
            "Iceland"
        ],
        "supportsDecimals": false
    },
    {
        "code": "JEP",
        "symbol": "£",
        "name": "Jersey pound",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "JMD",
        "symbol": "J$",
        "name": "Jamaican dollar",
        "countryKeywords": [
            "JMD",
            "JM",
            "jam",
            "Jamaica"
        ],
        "supportsDecimals": true
    },
    {
        "code": "JOD",
        "symbol": "JD",
        "name": "Jordanian dinar",
        "countryKeywords": [
            "JO",
            "jor",
            "Jordan",
            "JOD"
        ],
        "supportsDecimals": true
    },
    {
        "code": "JPY",
        "symbol": "¥",
        "name": "Japanese yen",
        "countryKeywords": [
            "JPY",
            "JP",
            "Japan",
            "jpn"
        ],
        "supportsDecimals": false
    },
    {
        "code": "KES",
        "symbol": "Ksh",
        "name": "Kenyan shilling",
        "countryKeywords": [
            "ken",
            "KES",
            "KE",
            "Kenya"
        ],
        "supportsDecimals": false
    },
    {
        "code": "KGS",
        "symbol": "KGS",
        "name": "Kyrgyzstani som",
        "countryKeywords": [
            "KGS",
            "KG",
            "Kyrgyzstan",
            "kgz"
        ],
        "supportsDecimals": true
    },
    {
        "code": "KHR",
        "symbol": "៛",
        "name": "Cambodian riel",
        "countryKeywords": [
            "khm",
            "KHR",
            "Cambodia",
            "KH"
        ],
        "supportsDecimals": true
    },
    {
        "code": "KMF",
        "symbol": "KMF",
        "name": "Comorian franc",
        "countryKeywords": [
            "com",
            "KM",
            "KMF",
            "Comoros"
        ],
        "supportsDecimals": false
    },
    {
        "code": "KPW",
        "symbol": "KPW",
        "name": "North Korean won",
        "countryKeywords": [
            "KPW",
            "KP",
            "Korea, Democratic People's Republic of",
            "prk"
        ],
        "supportsDecimals": true
    },
    {
        "code": "KRW",
        "symbol": "₩",
        "name": "South Korean won",
        "countryKeywords": [
            "KRW",
            "South Korea",
            "KR",
            "kor"
        ],
        "supportsDecimals": false
    },
    {
        "code": "KWD",
        "symbol": "ك",
        "name": "Kuwaiti dinar",
        "countryKeywords": [
            "KWD",
            "kwt",
            "KW",
            "Kuwait"
        ],
        "supportsDecimals": true
    },
    {
        "code": "KYD",
        "symbol": "$",
        "name": "Cayman Islands dollar",
        "countryKeywords": [
            "Cayman Islands",
            "cym",
            "KYD",
            "KY"
        ],
        "supportsDecimals": true
    },
    {
        "code": "KZT",
        "symbol": "₸",
        "name": "Kazakhstani tenge",
        "countryKeywords": [
            "KZT",
            "kaz",
            "Kazakhstan",
            "KZ"
        ],
        "supportsDecimals": true
    },
    {
        "code": "LAK",
        "symbol": "LAK",
        "name": "Lao kip",
        "countryKeywords": [
            "LA",
            "LAK",
            "lao",
            "Laos"
        ],
        "supportsDecimals": false
    },
    {
        "code": "LBP",
        "symbol": "LBP",
        "name": "Lebanon Pound",
        "countryKeywords": [
            "Lebanon",
            "LB",
            "lbn",
            "LBP"
        ],
        "supportsDecimals": true
    },
    {
        "code": "LKR",
        "symbol": "Sr",
        "name": "Sri Lankan rupee",
        "countryKeywords": [
            "LKR",
            "lka",
            "Sri Lanka",
            "LK"
        ],
        "supportsDecimals": true
    },
    {
        "code": "LRD",
        "symbol": "L$",
        "name": "Liberian dollar",
        "countryKeywords": [
            "Liberia",
            "LR",
            "lbr",
            "LRD"
        ],
        "supportsDecimals": true
    },
    {
        "code": "LSL",
        "symbol": "LSL",
        "name": "Lesotho loti",
        "countryKeywords": [
            "LSL",
            "LS",
            "lso",
            "Lesotho"
        ],
        "supportsDecimals": true
    },
    {
        "code": "LYD",
        "symbol": "LYD",
        "name": "Libyan dinar",
        "countryKeywords": [
            "lby",
            "LYD",
            "LY",
            "Libya"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MAD",
        "symbol": "د.م.",
        "name": "Moroccan dirham",
        "countryKeywords": [
            "MAD",
            "Western Sahara",
            "EH",
            "MA",
            "Morocco",
            "esh",
            "mar"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MDL",
        "symbol": "MDL",
        "name": "Moldovan leu",
        "countryKeywords": [
            "MDL",
            "MD",
            "Moldova",
            "mda"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MGA",
        "symbol": "MGA",
        "name": "Malagasy ariary",
        "countryKeywords": [
            "mdg",
            "MGA",
            "MG",
            "Madagascar"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MKD",
        "symbol": "ден",
        "name": "Macedonian denar",
        "countryKeywords": [
            "Macedonia, Former Yugoslav Republic of",
            "MKD",
            "mkd",
            "MK"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MMK",
        "symbol": "K",
        "name": "Myanmar kyat",
        "countryKeywords": [
            "MM",
            "Myanmar",
            "mmr",
            "MMK"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MNT",
        "symbol": "MNT",
        "name": "Mongolian tugrik",
        "countryKeywords": [
            "MN",
            "MNT",
            "Mongolia",
            "mng"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MOP",
        "symbol": "MOP",
        "name": "Macanese pataca",
        "countryKeywords": [
            "MO",
            "Macao",
            "mac",
            "MOP"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MRU",
        "symbol": "UM",
        "name": "Mauritanian ouguiya",
        "countryKeywords": [
            "MRU",
            "Mauritania",
            "MR",
            "mrt"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MUR",
        "symbol": "₨",
        "name": "Mauritian rupee",
        "countryKeywords": [
            "MU",
            "mus",
            "MUR",
            "Mauritius"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MVR",
        "symbol": "MVR",
        "name": "Maldivian rufiyaa",
        "countryKeywords": [
            "Maldives",
            "MVR",
            "MV",
            "mdv"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MWK",
        "symbol": "MWK",
        "name": "Malawian kwacha",
        "countryKeywords": [
            "MWK",
            "Malawi",
            "MW",
            "mwi"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MXN",
        "symbol": "Mex$",
        "name": "Mexican peso",
        "countryKeywords": [
            "mex",
            "MXN",
            "Mexico",
            "MX"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MYR",
        "symbol": "RM",
        "name": "Malaysian ringgit",
        "countryKeywords": [
            "mys",
            "MYR",
            "Malaysia",
            "MY"
        ],
        "supportsDecimals": true
    },
    {
        "code": "MZN",
        "symbol": "MT",
        "name": "Mozambican metical",
        "countryKeywords": [
            "MZN",
            "Mozambique",
            "moz",
            "MZ"
        ],
        "supportsDecimals": true
    },
    {
        "code": "NAD",
        "symbol": "$",
        "name": "Namibian dollar",
        "countryKeywords": [
            "NAD",
            "NA",
            "Namibia",
            "nam"
        ],
        "supportsDecimals": true
    },
    {
        "code": "NGN",
        "symbol": "₦",
        "name": "Nigerian naira",
        "countryKeywords": [
            "NGN",
            "NG",
            "nga",
            "Nigeria"
        ],
        "supportsDecimals": true
    },
    {
        "code": "NIO",
        "symbol": "NIO",
        "name": "Nicaraguan córdoba",
        "countryKeywords": [
            "Nicaragua",
            "NIO",
            "nic",
            "NI"
        ],
        "supportsDecimals": true
    },
    {
        "code": "NOK",
        "symbol": "kr",
        "name": "Norwegian krone",
        "countryKeywords": [
            "nor",
            "NO",
            "bvt",
            "BV",
            "Norway",
            "SJ",
            "sjm",
            "NOK",
            "Bouvet Island",
            "Svalbard and Jan Mayen"
        ],
        "supportsDecimals": true
    },
    {
        "code": "NPR",
        "symbol": "₨",
        "name": "Nepalese rupee",
        "countryKeywords": [
            "NPR",
            "NP",
            "npl",
            "Nepal"
        ],
        "supportsDecimals": false
    },
    {
        "code": "NZD",
        "symbol": "$",
        "name": "New Zealand dollar",
        "countryKeywords": [
            "nzl",
            "Tokelau",
            "Cook Islands",
            "NU",
            "CK",
            "Pitcairn Islands",
            "NZ",
            "Niue",
            "New Zealand",
            "tkl",
            "TK",
            "NZD",
            "pcn",
            "niu",
            "PN",
            "cok"
        ],
        "supportsDecimals": true
    },
    {
        "code": "OMR",
        "symbol": "OMR",
        "name": "Omani rial",
        "countryKeywords": [
            "omn",
            "OMR",
            "OM",
            "Oman"
        ],
        "supportsDecimals": true
    },
    {
        "code": "PAB",
        "symbol": "B/.",
        "name": "Panamanian balboa",
        "countryKeywords": [
            "PAB",
            "PA",
            "Panama",
            "pan"
        ],
        "supportsDecimals": true
    },
    {
        "code": "PEN",
        "symbol": "S/.",
        "name": "Peruvian sol",
        "countryKeywords": [
            "PE",
            "PEN",
            "per",
            "Peru"
        ],
        "supportsDecimals": true
    },
    {
        "code": "PGK",
        "symbol": "PGK",
        "name": "Papua New Guinean kina",
        "countryKeywords": [
            "Papua New Guinea",
            "PGK",
            "PG",
            "png"
        ],
        "supportsDecimals": true
    },
    {
        "code": "PHP",
        "symbol": "₱",
        "name": "Philippine peso",
        "countryKeywords": [
            "phl",
            "Philippines",
            "PH",
            "PHP"
        ],
        "supportsDecimals": true
    },
    {
        "code": "PKR",
        "symbol": "₨",
        "name": "Pakistani rupee",
        "countryKeywords": [
            "Pakistan",
            "PKR",
            "PK",
            "pak"
        ],
        "supportsDecimals": true
    },
    {
        "code": "PLN",
        "symbol": "zł",
        "name": "Polish złoty",
        "countryKeywords": [
            "PLN",
            "Poland",
            "PL",
            "pol"
        ],
        "supportsDecimals": true
    },
    {
        "code": "PYG",
        "symbol": "₲",
        "name": "Paraguay guaraní",
        "countryKeywords": [
            "pry",
            "PY",
            "Paraguay",
            "PYG"
        ],
        "supportsDecimals": false
    },
    {
        "code": "QAR",
        "symbol": "QR",
        "name": "Qatari riyal",
        "countryKeywords": [
            "QA",
            "QAR",
            "qat",
            "Qatar"
        ],
        "supportsDecimals": true
    },
    {
        "code": "RON",
        "symbol": "L",
        "name": "Romanian leu",
        "countryKeywords": [
            "RON",
            "Romania",
            "rou",
            "RO"
        ],
        "supportsDecimals": true
    },
    {
        "code": "RSD",
        "symbol": "РСД",
        "name": "Serbian dinar",
        "countryKeywords": [
            "RS",
            "RSD",
            "srb",
            "Serbia"
        ],
        "supportsDecimals": true
    },
    {
        "code": "RUB",
        "symbol": "руб",
        "name": "Russian rouble",
        "countryKeywords": [
            "rus",
            "Russian Federation",
            "RU",
            "RUB"
        ],
        "supportsDecimals": true
    },
    {
        "code": "RWF",
        "symbol": "RWF",
        "name": "Rwandan franc",
        "countryKeywords": [
            "RWF",
            "RW",
            "Rwanda",
            "rwa"
        ],
        "supportsDecimals": false
    },
    {
        "code": "SAR",
        "symbol": "SR",
        "name": "Saudi riyal",
        "countryKeywords": [
            "Saudi Arabia",
            "SAR",
            "sau",
            "SA"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SBD",
        "symbol": "SI$",
        "name": "Solomon Islands dollar",
        "countryKeywords": [
            "SBD",
            "slb",
            "SB",
            "Solomon Islands"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SCR",
        "symbol": "₨",
        "name": "Seychellois rupee",
        "countryKeywords": [
            "SC",
            "SCR",
            "Seychelles",
            "syc"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SDG",
        "symbol": "SDG",
        "name": "Sudanese Pound",
        "countryKeywords": [
            "SD",
            "SDG",
            "Sudan",
            "sdn"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SEK",
        "symbol": "kr",
        "name": "Swedish krona",
        "countryKeywords": [
            "swe",
            "SE",
            "Sweden",
            "SEK"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SGD",
        "symbol": "S$",
        "name": "Singapore dollar",
        "countryKeywords": [
            "SGD",
            "Singapore",
            "SG",
            "sgp"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SHP",
        "symbol": "£",
        "name": "Saint Helena pound",
        "countryKeywords": [
            "SH",
            "shn",
            "SHP",
            "Saint Helena"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SLL",
        "symbol": "SLL",
        "name": "Sierra Leonean leone",
        "countryKeywords": [
            "SLL",
            "SL",
            "Sierra Leone",
            "sle"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SLE",
        "symbol": "SLE",
        "name": "Sierra Leonean leone",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "SOS",
        "symbol": "Sh.So.",
        "name": "Somali shilling",
        "countryKeywords": [
            "som",
            "SOS",
            "Somalia",
            "SO"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SRD",
        "symbol": "$",
        "name": "Surinamese dollar",
        "countryKeywords": [
            "sur",
            "SRD",
            "Suriname",
            "SR"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SSP",
        "symbol": "SSP",
        "name": "South Sudanese pound",
        "countryKeywords": [
            "SS",
            "SSP",
            "South Sudan",
            "ssd"
        ],
        "supportsDecimals": true
    },
    {
        "code": "STD",
        "symbol": "STD",
        "name": "São Tomé & Príncipe dobra",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "STN",
        "symbol": "STN",
        "name": "São Tomé & Príncipe dobra",
        "countryKeywords": [
            "ST",
            "Sao Tome and Principe",
            "STN",
            "stp"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SVC",
        "symbol": "₡",
        "name": "Salvadoran colón",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "SYP",
        "symbol": "£",
        "name": "Syrian pound",
        "countryKeywords": [
            "Syrian Arab Republic",
            "SY",
            "SYP",
            "syr"
        ],
        "supportsDecimals": true
    },
    {
        "code": "SZL",
        "symbol": "SZL",
        "name": "Swazi lilangeni",
        "countryKeywords": [
            "SZL",
            "Swaziland",
            "SZ",
            "swz"
        ],
        "supportsDecimals": true
    },
    {
        "code": "THB",
        "symbol": "฿",
        "name": "Thai baht",
        "countryKeywords": [
            "TH",
            "tha",
            "Thailand",
            "THB"
        ],
        "supportsDecimals": true
    },
    {
        "code": "TJS",
        "symbol": "TJS",
        "name": "Tajikistani somoni",
        "countryKeywords": [
            "tjk",
            "TJ",
            "TJS",
            "Tajikistan"
        ],
        "supportsDecimals": true
    },
    {
        "code": "TMT",
        "symbol": "TMT",
        "name": "Turkmenistani manat",
        "countryKeywords": [
            "tkm",
            "TM",
            "TMT",
            "Turkmenistan"
        ],
        "supportsDecimals": true
    },
    {
        "code": "TND",
        "symbol": "TND",
        "name": "Tunisian dinar",
        "countryKeywords": [
            "TN",
            "TND",
            "tun",
            "Tunisia"
        ],
        "supportsDecimals": true
    },
    {
        "code": "TOP",
        "symbol": "TOP",
        "name": "Tongan pa'anga",
        "countryKeywords": [
            "ton",
            "TOP",
            "TO",
            "Tonga"
        ],
        "supportsDecimals": true
    },
    {
        "code": "TRY",
        "symbol": "TL",
        "name": "Turkish lira",
        "countryKeywords": [
            "tur",
            "Turkey",
            "TRY",
            "TR"
        ],
        "supportsDecimals": true
    },
    {
        "code": "TTD",
        "symbol": "TTD",
        "name": "Trinidad and Tobago dollar",
        "countryKeywords": [
            "TT",
            "TTD",
            "Trinidad and Tobago",
            "tto"
        ],
        "supportsDecimals": true
    },
    {
        "code": "TWD",
        "symbol": "NT$",
        "name": "Taiwanese New Taiwan dollar",
        "countryKeywords": [
            "TWD",
            "TW",
            "Taiwan",
            "twn"
        ],
        "supportsDecimals": false
    },
    {
        "code": "TZS",
        "symbol": "tzs",
        "name": "Tanzanian shilling",
        "countryKeywords": [
            "TZ",
            "Tanzania",
            "tza",
            "TZS"
        ],
        "supportsDecimals": true
    },
    {
        "code": "UAH",
        "symbol": "₴",
        "name": "Ukrainian hryvnia",
        "countryKeywords": [
            "Ukraine",
            "UA",
            "UAH",
            "ukr"
        ],
        "supportsDecimals": true
    },
    {
        "code": "UGX",
        "symbol": "Ush",
        "name": "Ugandan shilling",
        "countryKeywords": [
            "UG",
            "UGX",
            "Uganda",
            "uga"
        ],
        "supportsDecimals": false
    },
    {
        "code": "USD",
        "symbol": "$",
        "name": "United States dollar",
        "countryKeywords": [
            "Cambodia",
            "fin",
            "cck",
            "Paraguay",
            "lux",
            "uga",
            "Solomon Islands",
            "iot",
            "Montserrat",
            "deu",
            "Guadeloupe",
            "lva",
            "vir",
            "hnd",
            "nzl",
            "AD",
            "fji",
            "AE",
            "Falkland Islands",
            "AG",
            "Seychelles",
            "AI",
            "glp",
            "AL",
            "AM",
            "Bahrain",
            "AO",
            "wlf",
            "AQ",
            "AR",
            "AS",
            "AT",
            "AU",
            "Finland",
            "AX",
            "Faroe Islands",
            "AZ",
            "gmb",
            "BA",
            "BB",
            "Puerto Rico",
            "BE",
            "BF",
            "BG",
            "mys",
            "BH",
            "BJ",
            "myt",
            "BL",
            "BN",
            "BO",
            "BQ",
            "BS",
            "BT",
            "BW",
            "Cocos (Keeling) Islands",
            "Liechtenstein",
            "United States Virgin Islands",
            "gnb",
            "Bulgaria",
            "sen",
            "CA",
            "CC",
            "irl",
            "flk",
            "CH",
            "CI",
            "CK",
            "CL",
            "Côte d'Ivoire",
            "CN",
            "United Arab Emirates",
            "Kenya",
            "tha",
            "French Polynesia",
            "CR",
            "Saint Lucia",
            "CX",
            "CY",
            "CZ",
            "Mayotte",
            "Israel",
            "San Marino",
            "Tajikistan",
            "DE",
            "isl",
            "Gibraltar",
            "Cyprus",
            "DK",
            "bel",
            "kwt",
            "Northern Mariana Islands",
            "isr",
            "DM",
            "Malaysia",
            "ben",
            "DO",
            "Armenia",
            "bes",
            "DZ",
            "ita",
            "Turks and Caicos Islands",
            "bfa",
            "pan",
            "sgp",
            "ukr",
            "EC",
            "sgs",
            "EE",
            "che",
            "Ecuador",
            "reu",
            "EH",
            "chl",
            "chn",
            "hrv",
            "ES",
            "ET",
            "United States Minor Outlying Islands",
            "tjk",
            "vnm",
            "shn",
            "Italy",
            "Haiti",
            "FI",
            "FJ",
            "FK",
            "FM",
            "American Samoa",
            "FO",
            "bgr",
            "FR",
            "Vatican City",
            "umi",
            "civ",
            "tkl",
            "grc",
            "pcn",
            "GA",
            "GB",
            "hti",
            "Kyrgyzstan",
            "GE",
            "GF",
            "grl",
            "GG",
            "GH",
            "GI",
            "GL",
            "GM",
            "GN",
            "Uzbekistan",
            "GP",
            "GR",
            "bhs",
            "GS",
            "GT",
            "bhr",
            "GU",
            "GW",
            "GY",
            "dma",
            "tls",
            "Dominica",
            "hun",
            "bih",
            "Benin",
            "HK",
            "HN",
            "ago",
            "HR",
            "HT",
            "Portugal",
            "HU",
            "wsm",
            "Mongolia",
            "Latvia",
            "Morocco",
            "fra",
            "Guatemala",
            "ID",
            "nam",
            "per",
            "IE",
            "dnk",
            "gtm",
            "fro",
            "IL",
            "IM",
            "IN",
            "IO",
            "Tanzania",
            "slb",
            "IS",
            "Ghana",
            "IT",
            "sle",
            "India",
            "Canada",
            "Taiwan",
            "aia",
            "guf",
            "JE",
            "slv",
            "Germany",
            "gum",
            "fsm",
            "dom",
            "Fiji",
            "JM",
            "United States",
            "Guinea",
            "JP",
            "Micronesia, Federated States of",
            "Sao Tome and Principe",
            "guy",
            "mac",
            "Costa Rica",
            "Vietnam",
            "ton",
            "ncl",
            "smr",
            "KE",
            "KG",
            "KH",
            "mar",
            "blm",
            "KN",
            "USD",
            "Timor-Leste",
            "KR",
            "KW",
            "Switzerland",
            "KY",
            "Samoa",
            "Spain",
            "KZ",
            "phl",
            "LA",
            "LB",
            "LC",
            "Palau",
            "esh",
            "LI",
            "ury",
            "cok",
            "LK",
            "Estonia",
            "usa",
            "esp",
            "LR",
            "est",
            "LT",
            "LU",
            "LV",
            "Niue",
            "vut",
            "El Salvador",
            "MA",
            "alb",
            "MC",
            "ala",
            "eth",
            "mco",
            "ME",
            "Guam",
            "ner",
            "lao",
            "MH",
            "MK",
            "Tonga",
            "ML",
            "Western Sahara",
            "MN",
            "MO",
            "MP",
            "MQ",
            "MR",
            "MS",
            "MT",
            "MU",
            "MW",
            "MX",
            "MY",
            "Mauritius",
            "Norfolk Island",
            "spm",
            "nfk",
            "NA",
            "Sint Maarten (Dutch part)",
            "NC",
            "NE",
            "NF",
            "lbn",
            "NI",
            "lbr",
            "NL",
            "bol",
            "NO",
            "NP",
            "NR",
            "NU",
            "lca",
            "NZ",
            "Malta",
            "Ireland",
            "and",
            "rou",
            "cri",
            "Lithuania",
            "France",
            "mex",
            "srb",
            "kaz",
            "tto",
            "PA",
            "Nicaragua",
            "Norway",
            "PE",
            "PF",
            "Macao",
            "PG",
            "PH",
            "Uganda",
            "Mexico",
            "Suriname",
            "plw",
            "PL",
            "PM",
            "PN",
            "Greenland",
            "Saint Helena",
            "PR",
            "Papua New Guinea",
            "PT",
            "PW",
            "nic",
            "PY",
            "tun",
            "Kazakhstan",
            "Åland Islands",
            "Bahamas",
            "tur",
            "brb",
            "tuv",
            "Marshall Islands",
            "Mali",
            "Panama",
            "jam",
            "niu",
            "Laos",
            "zaf",
            "brn",
            "Argentina",
            "png",
            "Zambia",
            "stp",
            "mhl",
            "Guinea-Bissau",
            "RE",
            "Macedonia, Former Yugoslav Republic of",
            "Namibia",
            "Georgia",
            "Saint Kitts and Nevis",
            "RO",
            "RS",
            "RW",
            "twn",
            "pol",
            "Dubai",
            "SB",
            "SC",
            "sur",
            "SE",
            "Sweden",
            "South Georgia and the South Sandwich Islands",
            "SG",
            "ken",
            "are",
            "Malawi",
            "SH",
            "Andorra",
            "SI",
            "arg",
            "SK",
            "Poland",
            "SL",
            "SM",
            "SN",
            "uzb",
            "Tunisia",
            "btn",
            "arm",
            "SR",
            "ST",
            "SV",
            "SX",
            "nld",
            "svk",
            "svn",
            "Tuvalu",
            "TC",
            "Lebanon",
            "Azerbaijan",
            "TF",
            "Czech Republic",
            "Mauritania",
            "TH",
            "Guernsey",
            "TJ",
            "TK",
            "TL",
            "TN",
            "asm",
            "TO",
            "Australia",
            "Bonaire",
            "TR",
            "swe",
            "TT",
            "TV",
            "TW",
            "TZ",
            "mkd",
            "lie",
            "dza",
            "UA",
            "Iceland",
            "ata",
            "Gabon",
            "atf",
            "UG",
            "atg",
            "Luxembourg",
            "UM",
            "tza",
            "Algeria",
            "Jersey",
            "Slovenia",
            "cxr",
            "US",
            "jey",
            "kgz",
            "Antigua and Barbuda",
            "UY",
            "UZ",
            "pri",
            "sxm",
            "VA",
            "mli",
            "VC",
            "bwa",
            "VG",
            "khm",
            "Vanuatu",
            "idn",
            "VI",
            "prt",
            "mlt",
            "cym",
            "pry",
            "VN",
            "Honduras",
            "Antarctica",
            "cyp",
            "syc",
            "Nauru",
            "rwa",
            "aus",
            "VU",
            "aut",
            "Singapore",
            "lka",
            "French Guiana",
            "Christmas Island",
            "gab",
            "WF",
            "cze",
            "nor",
            "Netherlands",
            "China",
            "Martinique",
            "Saint Pierre and Miquelon",
            "WS",
            "Bhutan",
            "Romania",
            "mne",
            "Philippines",
            "mng",
            "npl",
            "mnp",
            "gbr",
            "British Virgin Islands",
            "British Indian Ocean Territory",
            "Montenegro",
            "Indonesia",
            "Angola",
            "Brunei Darussalam",
            "New Caledonia",
            "Greece",
            "Cayman Islands",
            "Guyana",
            "YT",
            "Chile",
            "Nepal",
            "Isle of Man",
            "ZA",
            "Ukraine",
            "vat",
            "Anguilla",
            "nru",
            "Turkey",
            "ZM",
            "Belgium",
            "South Africa",
            "Trinidad and Tobago",
            "Jamaica",
            "Peru",
            "Tokelau",
            "Hong Kong",
            "Pitcairn Islands",
            "Thailand",
            "aze",
            "geo",
            "Kuwait",
            "kna",
            "Croatia",
            "Sri Lanka",
            "Cook Islands",
            "Uruguay",
            "vct",
            "United Kingdom",
            "mrt",
            "Liberia",
            "Burkina Faso",
            "Saint Barthélemy",
            "pyf",
            "msr",
            "Wallis and Futuna",
            "zmb",
            "kor",
            "Austria",
            "South Korea",
            "Monaco",
            "ecu",
            "ggy",
            "gha",
            "Réunion",
            "Hungary",
            "Japan",
            "mtq",
            "Albania",
            "New Zealand",
            "Senegal",
            "Ethiopia",
            "gib",
            "hkg",
            "mus",
            "Sierra Leone",
            "imn",
            "Bolivia",
            "gin",
            "vgb",
            "can",
            "tca",
            "Gambia",
            "Slovakia",
            "Serbia",
            "Bosnia and Herzegovina",
            "ind",
            "Niger",
            "Rwanda",
            "jpn",
            "French Southern Territories",
            "ltu",
            "Barbados",
            "Saint Vincent and the Grenadines",
            "Botswana",
            "Denmark",
            "Dominican Republic",
            "mwi"
        ],
        "supportsDecimals": true
    },
    {
        "code": "UYU",
        "symbol": "$U",
        "name": "Uruguayan peso",
        "countryKeywords": [
            "UYU",
            "UY",
            "Uruguay",
            "ury"
        ],
        "supportsDecimals": true
    },
    {
        "code": "UYW",
        "symbol": "UYW",
        "name": "Unidad Previsional",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "UZS",
        "symbol": "UZS",
        "name": "Uzbekistani som",
        "countryKeywords": [
            "UZ",
            "Uzbekistan",
            "uzb",
            "UZS"
        ],
        "supportsDecimals": true
    },
    {
        "code": "VES",
        "symbol": "Bs.",
        "name": "Venezuelan bolívar soberano",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "VND",
        "symbol": "VND",
        "name": "Vietnamese dong",
        "countryKeywords": [
            "Vietnam",
            "vnm",
            "VN",
            "VND"
        ],
        "supportsDecimals": false
    },
    {
        "code": "VUV",
        "symbol": "VUV",
        "name": "Vanuatu vatu",
        "countryKeywords": [
            "Vanuatu",
            "vut",
            "VUV",
            "VU"
        ],
        "supportsDecimals": false
    },
    {
        "code": "WST",
        "symbol": "WST",
        "name": "Samoan tala",
        "countryKeywords": [
            "wsm",
            "WST",
            "WS",
            "Samoa"
        ],
        "supportsDecimals": true
    },
    {
        "code": "XAF",
        "symbol": "XAF",
        "name": "Central African CFA franc",
        "countryKeywords": [
            "CF",
            "CG",
            "Cameroone",
            "Chad",
            "gab",
            "cmr",
            "caf",
            "GQ",
            "CM",
            "gnq",
            "Equatorial Guinea",
            "Congo",
            "TD",
            "Gabon",
            "tcd",
            "cog",
            "GA",
            "Central African Republic",
            "XAF"
        ],
        "supportsDecimals": false
    },
    {
        "code": "XCD",
        "symbol": "$",
        "name": "East Caribbean dollar",
        "countryKeywords": [
            "DM",
            "lca",
            "msr",
            "Grenada",
            "Montserrat",
            "atg",
            "grd",
            "GD",
            "kna",
            "Antigua and Barbuda",
            "KN",
            "AG",
            "vct",
            "MS",
            "AI",
            "Anguilla",
            "VC",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "LC",
            "XCD",
            "aia",
            "dma",
            "Saint Kitts and Nevis",
            "Dominica"
        ],
        "supportsDecimals": true
    },
    {
        "code": "XCG",
        "symbol": "Cg",
        "name": "Caribbean Guilder",
        "countryKeywords": [],
        "supportsDecimals": true
    },
    {
        "code": "XOF",
        "symbol": "XOF",
        "name": "West African CFA franc",
        "countryKeywords": [
            "Benin",
            "BF",
            "BJ",
            "nga",
            "ben",
            "civ",
            "Mali",
            "gnb",
            "ner",
            "SN",
            "Nigeria",
            "bfa",
            "sen",
            "tgo",
            "ML",
            "Togo",
            "Niger",
            "CI",
            "Côte d'Ivoire",
            "mli",
            "XOF",
            "GW",
            "Guinea-Bissau",
            "TG",
            "Burkina Faso",
            "Senegal",
            "NE",
            "NG"
        ],
        "supportsDecimals": false
    },
    {
        "code": "XPF",
        "symbol": "XPF",
        "name": "CFP franc",
        "countryKeywords": [
            "wlf",
            "NC",
            "PF",
            "ncl",
            "pyf",
            "Wallis and Futuna",
            "New Caledonia",
            "XPF",
            "French Polynesia",
            "WF"
        ],
        "supportsDecimals": false
    },
    {
        "code": "YER",
        "symbol": "﷼",
        "name": "Yemeni rial",
        "countryKeywords": [
            "yem",
            "YER",
            "YE",
            "Yemen"
        ],
        "supportsDecimals": true
    },
    {
        "code": "ZAR",
        "symbol": "R",
        "name": "South African rand",
        "countryKeywords": [
            "ZA",
            "South Africa",
            "ZAR",
            "zaf"
        ],
        "supportsDecimals": true
    },
    {
        "code": "ZMW",
        "symbol": "ZMW",
        "name": "Zambian kwacha",
        "countryKeywords": [
            "ZM",
            "ZMW",
            "Zambia",
            "zmb"
        ],
        "supportsDecimals": true
    },
    {
        "code": "ZWG",
        "symbol": "ZWG",
        "name": "Zimbabwe Gold",
        "countryKeywords": [],
        "supportsDecimals": true
    }
]

module.exports = { paypalSupportedCurrencies, wiseSupportedCurrencies }